In [183]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


In [184]:
df = pd.read_csv("train.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

## pd.cut

pd.cut(x, bins, right=True, labels=None, retbins=False, precision=3, include_lowest=False)[source]

np.random.randint(low, high=None, size=None, dtype='l')

## 乱数でヒストグラム練習

In [187]:
np.random.randint(10,size=100)

array([5, 1, 4, 6, 4, 4, 1, 3, 9, 1, 1, 8, 6, 9, 3, 1, 9, 6, 6, 7, 2, 6, 3,
       9, 4, 5, 8, 9, 0, 0, 5, 2, 3, 3, 4, 8, 6, 7, 2, 3, 4, 7, 8, 4, 1, 3,
       4, 5, 6, 5, 4, 7, 3, 8, 5, 5, 1, 3, 8, 7, 0, 7, 9, 8, 8, 1, 5, 2, 1,
       1, 0, 7, 9, 5, 1, 3, 6, 1, 8, 7, 1, 0, 7, 0, 9, 1, 6, 0, 8, 3, 5, 4,
       0, 7, 0, 3, 1, 0, 6, 0])

In [188]:
np.random.rand(1) * 40 + 30

array([ 55.27594083])

In [198]:
age_samples = np.random.randint(1,high=101,size=100)
age_samples

array([ 37,  16,  27,  53,  86,   5,  29,  90,  17,  40,  76,  74,  13,
        87,  46,  24,  46,  84,  63,  65,  38,  13,  37,  89,  87,  14,
        17,  54,  65,  54,  99,  85,   3,  24,  26,  57,   1,   7,  98,
        54,  51, 100,  34,  19,  72,  34,  62,  81,  49,  54,  26,  92,
        91,  25,   7,  79,  99,  19,  30,  66,  48,  55,  46,  28,  94,
        39,  93,  86,  84,  78,  65,  55,  33,  56,  42,   8,  10,  22,
        95,  78,  13,  24,  42,  11,  94,  67,  32,  11,  60,  23,  95,
        55,  21,  85,  21,  60,  60,  99,  65,  38])

In [199]:
age_samples =  pd.DataFrame({'Age': age_samples})
age_samples

Age
0    37
1    16
2    27
3    53
4    86
5     5
6    29
7    90
8    17
9    40
10   76
11   74
12   13
13   87
14   46
15   24
16   46
17   84
18   63
19   65
20   38
21   13
22   37
23   89
24   87
25   14
26   17
27   54
28   65
29   54
..  ...
70   65
71   55
72   33
73   56
74   42
75    8
76   10
77   22
78   95
79   78
80   13
81   24
82   42
83   11
84   94
85   67
86   32
87   11
88   60
89   23
90   95
91   55
92   21
93   85
94   21
95   60
96   60
97   99
98   65
99   38

[100 rows x 1 columns]

In [200]:
age_samples = pd.cut(age_samples['Age'], [0,10,20,30,40,50,60,70,80,90,100])
age_samples

0      (30, 40]
1      (10, 20]
2      (20, 30]
3      (50, 60]
4      (80, 90]
5       (0, 10]
6      (20, 30]
7      (80, 90]
8      (10, 20]
9      (30, 40]
10     (70, 80]
11     (70, 80]
12     (10, 20]
13     (80, 90]
14     (40, 50]
15     (20, 30]
16     (40, 50]
17     (80, 90]
18     (60, 70]
19     (60, 70]
20     (30, 40]
21     (10, 20]
22     (30, 40]
23     (80, 90]
24     (80, 90]
25     (10, 20]
26     (10, 20]
27     (50, 60]
28     (60, 70]
29     (50, 60]
        ...    
70     (60, 70]
71     (50, 60]
72     (30, 40]
73     (50, 60]
74     (40, 50]
75      (0, 10]
76      (0, 10]
77     (20, 30]
78    (90, 100]
79     (70, 80]
80     (10, 20]
81     (20, 30]
82     (40, 50]
83     (10, 20]
84    (90, 100]
85     (60, 70]
86     (30, 40]
87     (10, 20]
88     (50, 60]
89     (20, 30]
90    (90, 100]
91     (50, 60]
92     (20, 30]
93     (80, 90]
94     (20, 30]
95     (50, 60]
96     (50, 60]
97    (90, 100]
98     (60, 70]
99     (30, 40]
Name: Age, dtype: catego

In [201]:
age_samples.value_counts(sort=False)

(0, 10]       7
(10, 20]     11
(20, 30]     14
(30, 40]     10
(40, 50]      7
(50, 60]     14
(60, 70]      8
(70, 80]      6
(80, 90]     11
(90, 100]    12
Name: Age, dtype: int64

## 小課題1

### 1.

In [203]:
age_samples = np.random.randint(1,high=101,size=100)
age_samples = pd.DataFrame({'Age': age_samples})
age_samples = pd.cut(age_samples['Age'], [0,10,20,30,40,50,60,70,80,90,100],include_lowest=True, right=False)
all_frequencies = age_samples.value_counts(sort=False)

In [208]:
def relative_frequency(all_frequencies, all_samples_number):
    
    return all_frequencies / all_samples_number
        
rf = relative_frequency(all_frequencies, 100)

In [209]:
rf

[0, 10)      0.10
[10, 20)     0.10
[20, 30)     0.10
[30, 40)     0.10
[40, 50)     0.08
[50, 60)     0.12
[60, 70)     0.09
[70, 80)     0.11
[80, 90)     0.09
[90, 100)    0.11
Name: Age, dtype: float64

### 2.

In [210]:
all_frequencies.cumsum()

[0, 10)       10
[10, 20)      20
[20, 30)      30
[30, 40)      40
[40, 50)      48
[50, 60)      60
[60, 70)      69
[70, 80)      80
[80, 90)      89
[90, 100)    100
Name: Age, dtype: int64

### 3.

In [211]:
relative_frequency(all_frequencies.cumsum(), 100)

[0, 10)      0.10
[10, 20)     0.20
[20, 30)     0.30
[30, 40)     0.40
[40, 50)     0.48
[50, 60)     0.60
[60, 70)     0.69
[70, 80)     0.80
[80, 90)     0.89
[90, 100)    1.00
Name: Age, dtype: float64

* * * * * * * * * * * * * * * * * * * *

* * * * * * * * * * * 

In [140]:
a =np.random.normal(size=(7,8))

In [142]:
a > 1

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False,  True,  True],
       [False, False, False, False,  True, False, False,  True],
       [ True, False, False, False, False, False,  True,  True],
       [ True, False,  True, False, False, False, False, False]], dtype=bool)

In [149]:
a = np.array([[1,2,3],[4,5,6]])

In [150]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [151]:
np.cumsum(a,axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [152]:
np.cumsum(a,axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])