In [1]:
import numpy as np

In [6]:
a = np.array([1,2])

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
a

array([1, 2])

In [65]:
a[None,:]

array([[1, 2]])

In [67]:
a[None,:].ndim

2

In [70]:
a[:,np.newaxis]

array([[1],
       [2]])

In [69]:
a[:,np.newaxis].ndim

2

In [71]:
d=np.array(
      [[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]])

In [72]:
d.ndim

3

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
b.ndim

2

In [26]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [62]:
b[:,np.newaxis]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [55]:
b[:,None] #np.newaxisと一緒。

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [63]:
b.ndim

2

In [60]:
x = np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
x.ndim

2

In [13]:
a.shape

(2,)

In [14]:
a.ndim

1

In [15]:
b.shape

(2, 3)

In [16]:
b.ndim

2

* * * * * 

In [18]:
c = np.arange(6).reshape((3, 2))

In [20]:
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
c.shape

(3, 2)

In [22]:
c.ndim

2

In [30]:
d = np.array([b.T, c])

In [31]:
d.shape

(2, 3, 2)

In [32]:
d

array([[[1, 4],
        [2, 5],
        [3, 6]],

       [[0, 1],
        [2, 3],
        [4, 5]]])

In [34]:
d.sum(axis=0).shape == (3, 2)

True

In [35]:
d.sum(axis=1).shape == (2, 2)

True

In [36]:
d.sum(axis=2).shape == (2, 3)

True

In [37]:
d.sum(axis=0)

array([[ 1,  5],
       [ 4,  8],
       [ 7, 11]])

In [38]:
d.sum(axis=1)

array([[ 6, 15],
       [ 6,  9]])

In [39]:
d.sum(axis=2)

array([[5, 7, 9],
       [1, 5, 9]])

In [40]:
#今回のデータはアメリカのボストン近郊での住宅の価格に関するデータです。
import numpy as np
from sklearn.datasets import load_boston
boston = load_boston()
import pandas as pd
X=pd.DataFrame(boston.data[:100,:], columns=boston.feature_names)
y=boston.target[:100]

In [41]:
x=X['LSTAT'].values

In [42]:
x

array([  4.98,   9.14,   4.03,   2.94,   5.33,   5.21,  12.43,  19.15,
        29.93,  17.1 ,  20.45,  13.27,  15.71,   8.26,  10.26,   8.47,
         6.58,  14.67,  11.69,  11.28,  21.02,  13.83,  18.72,  19.88,
        16.3 ,  16.51,  14.81,  17.28,  12.8 ,  11.98,  22.6 ,  13.04,
        27.71,  18.35,  20.34,   9.68,  11.41,   8.77,  10.13,   4.32,
         1.98,   4.84,   5.81,   7.44,   9.55,  10.21,  14.15,  18.8 ,
        30.81,  16.2 ,  13.45,   9.43,   5.28,   8.43,  14.8 ,   4.81,
         5.77,   3.95,   6.86,   9.22,  13.15,  14.44,   6.73,   9.5 ,
         8.05,   4.67,  10.24,   8.1 ,  13.09,   8.79,   6.72,   9.88,
         5.52,   7.54,   6.78,   8.94,  11.97,  10.27,  12.34,   9.1 ,
         5.29,   7.22,   6.72,   7.51,   9.62,   6.53,  12.86,   8.44,
         5.5 ,   5.7 ,   8.81,   8.2 ,   8.16,   6.21,  10.59,   6.65,
        11.34,   4.21,   3.57,   6.19])

In [43]:
x.ndim

1

In [54]:
# xをベクトルから行列に変換
x[:,None]

array([[  4.98],
       [  9.14],
       [  4.03],
       [  2.94],
       [  5.33],
       [  5.21],
       [ 12.43],
       [ 19.15],
       [ 29.93],
       [ 17.1 ],
       [ 20.45],
       [ 13.27],
       [ 15.71],
       [  8.26],
       [ 10.26],
       [  8.47],
       [  6.58],
       [ 14.67],
       [ 11.69],
       [ 11.28],
       [ 21.02],
       [ 13.83],
       [ 18.72],
       [ 19.88],
       [ 16.3 ],
       [ 16.51],
       [ 14.81],
       [ 17.28],
       [ 12.8 ],
       [ 11.98],
       [ 22.6 ],
       [ 13.04],
       [ 27.71],
       [ 18.35],
       [ 20.34],
       [  9.68],
       [ 11.41],
       [  8.77],
       [ 10.13],
       [  4.32],
       [  1.98],
       [  4.84],
       [  5.81],
       [  7.44],
       [  9.55],
       [ 10.21],
       [ 14.15],
       [ 18.8 ],
       [ 30.81],
       [ 16.2 ],
       [ 13.45],
       [  9.43],
       [  5.28],
       [  8.43],
       [ 14.8 ],
       [  4.81],
       [  5.77],
       [  3.95],
       [  6.86

In [46]:
x[:,None].ndim

2

In [52]:
x[None,:]
# x.transpose()

array([[  4.98,   9.14,   4.03,   2.94,   5.33,   5.21,  12.43,  19.15,
         29.93,  17.1 ,  20.45,  13.27,  15.71,   8.26,  10.26,   8.47,
          6.58,  14.67,  11.69,  11.28,  21.02,  13.83,  18.72,  19.88,
         16.3 ,  16.51,  14.81,  17.28,  12.8 ,  11.98,  22.6 ,  13.04,
         27.71,  18.35,  20.34,   9.68,  11.41,   8.77,  10.13,   4.32,
          1.98,   4.84,   5.81,   7.44,   9.55,  10.21,  14.15,  18.8 ,
         30.81,  16.2 ,  13.45,   9.43,   5.28,   8.43,  14.8 ,   4.81,
          5.77,   3.95,   6.86,   9.22,  13.15,  14.44,   6.73,   9.5 ,
          8.05,   4.67,  10.24,   8.1 ,  13.09,   8.79,   6.72,   9.88,
          5.52,   7.54,   6.78,   8.94,  11.97,  10.27,  12.34,   9.1 ,
          5.29,   7.22,   6.72,   7.51,   9.62,   6.53,  12.86,   8.44,
          5.5 ,   5.7 ,   8.81,   8.2 ,   8.16,   6.21,  10.59,   6.65,
         11.34,   4.21,   3.57,   6.19]])